/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LaundryUAS;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class formPelanggan extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn =Koneksi.getKoneksi();
    /**
     * Creates new form formPelanggan
     */
    public formPelanggan() {
        initComponents();
        judul();
        Tampil_ID();
        readData("");
        tdId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNoHp = new javax.swing.JTextField();
        tfTglTerima = new javax.swing.JTextField();
        tfTglPengambilan = new javax.swing.JTextField();
        cbLayanan = new javax.swing.JComboBox();
        tbTambah = new javax.swing.JToggleButton();
        tbUbah = new javax.swing.JToggleButton();
        tbHapus = new javax.swing.JToggleButton();
        tbReset = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        cbPilihan = new javax.swing.JComboBox();
        tdId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LAUNDRY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 60));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setText("NAMA");

        jLabel3.setText("No.hp");

        jLabel4.setText("Tgl. Terima");

        jLabel5.setText("Tgl. Pengambilan");

        jLabel6.setText("Pilihan");

        jLabel7.setText("Layanan");

        tfTglTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTglTerimaActionPerformed(evt);
            }
        });

        cbLayanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cuci kering", "cuci kering lipat" }));

        tbTambah.setBackground(new java.awt.Color(204, 204, 204));
        tbTambah.setText("Tambah");
        tbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahActionPerformed(evt);
            }
        });

        tbUbah.setText("Ubah");
        tbUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUbahActionPerformed(evt);
            }
        });

        tbHapus.setText("Hapus");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });

        tbReset.setText("Reset");
        tbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbResetActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        cbPilihan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kiloan", "Satuan" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(tbTambah))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tbUbah)
                                .addGap(24, 24, 24)
                                .addComponent(tbHapus)
                                .addGap(18, 18, 18)
                                .addComponent(tbReset))
                            .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTglPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tdId, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTglTerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTglPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTambah)
                    .addComponent(tbUbah)
                    .addComponent(tbHapus)
                    .addComponent(tbReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 590, 560));

        setSize(new java.awt.Dimension(608, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void judul(){
        Object[] judul = {"id","Nama","No.Hp","tgl terima","tg kembali","pilihan","layanan"};
        tabModel=new DefaultTableModel(null,judul);
        tabel.setModel(tabModel);
        
    }
    
    public void readData(String where){
        try{
            st =cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs=st.executeQuery("SELECT * FROM pelanggan "+ where);
            
            while(rs.next()){
                Object[]data={
                  
                    rs.getString("id_pelanggan"),
                    rs.getString("nama"),
                    rs.getString("no_hp"),
                    rs.getString("tgl_terima"),
                    rs.getString("tgl_pengembalian"),
                    rs.getString("pilihan"),
                    rs.getString("layanan")
                    
                };
                
                tabModel.addRow(data);
            }
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    private void tfTglTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTglTerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTglTerimaActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        tdId.setText(tabel.getValueAt(tabel.getSelectedRow(), 0).toString());
        tfNama.setText(tabel.getValueAt(tabel.getSelectedRow(),1).toString());
          tfNoHp.setText(tabel.getValueAt(tabel.getSelectedRow(),2).toString());
            tfTglTerima.setText(tabel.getValueAt(tabel.getSelectedRow(),3).toString());
              tfTglPengambilan.setText(tabel.getValueAt(tabel.getSelectedRow(),4).toString());
                cbPilihan.setSelectedItem(tabel.getValueAt(tabel.getSelectedRow(),5).toString());
              cbLayanan.setSelectedItem(tabel.getValueAt(tabel.getSelectedRow(),6).toString());
        
    }//GEN-LAST:event_tabelMouseClicked

    private void Tampil_ID() {
    try {
       
        String sql ="SELECT id_pelanggan as a FROM pelanggan order by id_pelanggan desc";
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
             
            if (rs.next()) {
                String No_Urut = rs.getString("a");
                int a = Integer.parseInt(No_Urut);
                int panjang = No_Urut.length();
                for (int i = 0; i < 2 - panjang; i++) {
                    a = a;
                }
              
                tdId.setText(Integer.toString(a + 1));
            } else {
                tdId.setText("1");
                
            }
        rs.close();
    } catch (Exception e) {
    }
}
    private void tbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahActionPerformed
        // TODO add your handling code here:
            try {
        st = cn.createStatement();
        st.executeUpdate("INSERT INTO pelanggan VALUES('" + tdId.getText()+ "','" + tfNama.getText() + "','"
            + tfNoHp.getText()+ "','"
            + tfTglTerima.getText()+ "','"
            + tfTglPengambilan.getText()+ "','"
            + cbPilihan.getSelectedItem()+ "','"
            + cbLayanan.getSelectedItem()+ "')");
        readData("");
        JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
        tfNama.setText("");
        tfNoHp.setText("");
        tfTglTerima.setText("");
        tfTglPengambilan.setText("");
        cbPilihan.setSelectedItem("");
        cbLayanan.setSelectedItem("");
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbTambahActionPerformed

    private void tbUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUbahActionPerformed
        // TODO add your handling code here:
        try{
            st=cn.createStatement();
            st.executeUpdate("update pelanggan SET id_pelanggan= '"+tdId.getText()+"', nama = '"+tfNama.getText()+"', no_hp = '"+tfNoHp.getText()+"', tgl_terima =  '"+tfTglTerima.getText()+"',tgl_pengembalian = '"
                    +tfTglPengambilan.getText()+"', pilihan = '"+cbPilihan.getSelectedItem()+"', layanan = '"+cbLayanan.getSelectedItem()+
                    "' WHERE id_pelanggan = '"+tdId.getText()+"'");
            readData("");
            JOptionPane.showMessageDialog(null, "update berhasil");
            reset();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tbUbahActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
        try {
            int jawab;
            
            if ((jawab= JOptionPane.showConfirmDialog(null, " ingin meghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM pelanggan WHERE id_pelanggan='"
                    + tabModel.getValueAt(tabel.getSelectedRow(),0) +"'");
                readData("");
                reset();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbHapusActionPerformed
 public void reset (){
     tdId.setText("");
    tfNama.setText("");
    tfNoHp.setText("");
    tfTglTerima.setText("");
    tfTglPengambilan.setText("");
    cbPilihan.setSelectedItem("");
    cbLayanan.setSelectedItem("");
    
    }
    
    private void tbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_tbResetActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbLayanan;
    private javax.swing.JComboBox cbPilihan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JToggleButton tbHapus;
    private javax.swing.JToggleButton tbReset;
    private javax.swing.JToggleButton tbTambah;
    private javax.swing.JToggleButton tbUbah;
    private javax.swing.JTextField tdId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoHp;
    private javax.swing.JTextField tfTglPengambilan;
    private javax.swing.JTextField tfTglTerima;
    // End of variables declaration//GEN-END:variables
}
